feat: Add image loading message in main.go
Revert rollback: remove log

chore: Improve revert commit detection and amend message

feat: Add lazy loading for images in load_image.go

rollback: load_image

chore: Remove file.Close() in load_image.go

backing defer

feat: Refactor revert commit handling in detect_reverts.yml

chore: Remove JPEG image decoding in load_image.go

rollback comment

chore: Remove unnecessary code in main.go

feat: Improve revert commit handling in detect_reverts.yml

chore: Remove unnecessary code and comments in main.go

Refactor main.go to improve code readability and remove unnecessary code

chore: Verify commit message in detect_reverts.yml

chore: line code

fix: remove comment (this is a revert)

chore: add pattern to commit revert

diff --git a/.github/workflows/detect_reverts.yml b/.github/workflows/detect_reverts.yml
--- a/.github/workflows/detect_reverts.yml
+++ b/.github/workflows/detect_reverts.yml
@@ -1,4 +1,4 @@
-name: Detect Reverts and Amend Commit Message
+name: Detect Reverts and Verify Commit Message
 
 on: [push]
 
@@ -31,32 +31,14 @@ jobs:
         OLD_COMMIT_HASH: ${{ github.event.before }}
         NEW_COMMIT_HASH: ${{ github.sha }}
 
-    - name: Configure Git user
-      if: steps.detect_reverts.outputs.revert_commit != ''
-      run: |
-        git config user.name "GitHub Actions"
-        git config user.email "actions@github.com"
-
-    - name: Get branch name
-      id: get_branch
-      run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"
-
-    - name: Amend commit message
+    - name: Check commit message
       if: steps.detect_reverts.outputs.revert_commit != ''
       run: |
         REVERT_COMMIT=${{ steps.detect_reverts.outputs.revert_commit }}
-        BRANCH_NAME=${{ steps.get_branch.outputs.branch }}
-        echo "Revert commit detected: $REVERT_COMMIT"
-        git checkout $BRANCH_NAME
-        GIT_SEQUENCE_EDITOR="sed -i 's/pick ${REVERT_COMMIT:0:7}/edit ${REVERT_COMMIT:0:7}/'" git rebase -i --root
-        git commit --amend -m "Revert $(git log -1 --pretty=%B --skip 1)"
-        git rebase --continue
-
-    - name: Push changes
-      if: steps.detect_reverts.outputs.revert_commit != ''
-      env:
-        GH_TOKEN: ${{ secrets.GH_TOKEN }}
-      run: |
-        BRANCH_NAME=${{ steps.get_branch.outputs.branch }}
-        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
-        git push origin HEAD:$BRANCH_NAME --force
+        COMMIT_MESSAGE=$(git log -1 --pretty=%B $REVERT_COMMIT)
+        if [[ ! $COMMIT_MESSAGE =~ ^Revert ]]; then
+          echo "Error: Revert commit detected: $REVERT_COMMIT with incorrect message, expected start with 'Revert'"
+          exit 1
+        else
+          echo "Revert commit detected: $REVERT_COMMIT with correct message"
+        fi
