feat: check merge

diff --git a/.github/workflows/detect_reverts.yml b/.github/workflows/detect_reverts.yml
--- a/.github/workflows/detect_reverts.yml
+++ b/.github/workflows/detect_reverts.yml
@@ -1,6 +1,10 @@
-name: Detect Reverts and Verify Commit Message
+name: Detect Reverts After Merge
 
-on: [push]
+on:
+  push:
+    branches:
+      - main
+      - master
 
 jobs:
   detect_reverts:
@@ -23,22 +27,14 @@ jobs:
     - name: Run detect_reverts.py
       id: detect_reverts
       run: |
-        OLD_COMMIT_HASH=$(git rev-parse HEAD~1)
         NEW_COMMIT_HASH=$(git rev-parse HEAD)
         REVERT_COMMIT=$(python scripts/detect_reverts.py)
         echo "::set-output name=revert_commit::$REVERT_COMMIT"
       env:
-        OLD_COMMIT_HASH: ${{ github.event.before }}
         NEW_COMMIT_HASH: ${{ github.sha }}
 
-    - name: Check commit message
+    - name: Check revert commit
       if: steps.detect_reverts.outputs.revert_commit != ''
       run: |
-        REVERT_COMMIT=${{ steps.detect_reverts.outputs.revert_commit }}
-        COMMIT_MESSAGE=$(git log -1 --pretty=%B $REVERT_COMMIT)
-        if [[ ! $COMMIT_MESSAGE =~ ^Revert ]]; then
-          echo "Error: Revert commit detected: $REVERT_COMMIT with incorrect message, expected start with 'Revert'"
-          exit 1
-        else
-          echo "Revert commit detected: $REVERT_COMMIT with correct message"
-        fi
+        echo "Revert commit detected: ${{ steps.detect_reverts.outputs.revert_commit }}"
+        exit 1  # Fail the job if a revert commit is detected
