Refactor revert commit handling and improve detection in detect_reverts.yml

diff --git a/.github/workflows/detect_reverts.yml b/.github/workflows/detect_reverts.yml
--- a/.github/workflows/detect_reverts.yml
+++ b/.github/workflows/detect_reverts.yml
@@ -29,8 +29,18 @@ jobs:
       env:
         NEW_COMMIT_HASH: ${{ github.sha }}
 
-    - name: Check revert commit
+    - name: Check commit message
       if: steps.detect_reverts.outputs.revert_commit != ''
       run: |
-        echo "Revert commit detected: ${{ steps.detect_reverts.outputs.revert_commit }}"
-        exit 1  # Fail the job if a revert commit is detected
+        REVERT_COMMIT=${{ steps.detect_reverts.outputs.revert_commit }}
+        if [[ $REVERT_COMMIT == "None" || $REVERT_COMMIT == "" ]]; then
+          echo "No revert commit detected"
+          exit 0
+        fi
+        COMMIT_MESSAGE=$(git log -1 --pretty=%B $REVERT_COMMIT)
+        if [[ ! $COMMIT_MESSAGE =~ ^Revert ]]; then
+          echo "Error: Revert commit detected: $REVERT_COMMIT with incorrect message, expected start with 'Revert'"
+          exit 1
+        else
+          echo "Revert commit detected: $REVERT_COMMIT with correct message"
+        fi
